# NumPy

Ya sabemos bastantes cosas de esta librería, pero vamos a recordar algunas y, más que nada, hacer un compendio de sus métodos más piolas.

In [1]:
import numpy as np

***

Entre estas líneas voy a garabatear algunas cosas típicas de dudas.

In [11]:
array1 = np.array([[1, 2, 3]])
array1

array([[1, 2, 3]])

In [12]:
array2 = np.array([[1], [2], [3]])
array2

array([[1],
       [2],
       [3]])

In [13]:
array1 == array2

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [14]:
array1 is array2

False

In [15]:
array1.T is array2

False

In [16]:
array1.T

array([[1],
       [2],
       [3]])

In [17]:
array1.T == array2

array([[ True],
       [ True],
       [ True]])

In [19]:
array_a = np.array([1, 2, 3])
array_b = np.array([[1, 2, 3]])
print(array_a.shape)
print(array_b.shape)

(3,)
(1, 3)


***

Vamos a hacer una pequeña listita con funciones copadas y útiles

In [24]:
# Matriz llena de cero
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# Matriz llena de 1
np.ones([3, 2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
# Matriz con valores sin inicializar (útil por la velocidad)
# Nota: hay que asegurarse de ponerle valores luego!
np.empty([3, 3])

array([[1.06135352e-312, 0.00000000e+000, 1.06395697e+224],
       [1.25909727e-075, 2.31805409e-056, 1.25585851e-075],
       [1.90193486e+185, 4.29894906e-086, 6.27207943e-310]])

In [31]:
# Array a partir de un rango de valores
# Este array tiene elementos equiespaciados
np.arange(5)

array([0, 1, 2, 3, 4])

In [30]:
# np.arange(start, stop, step)
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [33]:
# Array con elementos equiespaciados
# Nota: acá se especifica en qué numero empieza y termina y la cant. de puntos
np.linspace(1, 10, num = 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [36]:
np.linspace(0, 1, num = 9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

Resumiendo lo anterior:<br>
 - np.zeros: matriz de 0's
 - np.ones: matriz de 1's
 - np.empty: matriz sin inicializar
 - np.arange: array equiespaciado (start, stop, step)
 - np.linspace: array equiespaciado (start, stop, nro_de_puntos)

## Más comandos útiles

Vamos a hacer como más arriba, un resumen rápido de las funciones.

<u>Agregar, borrar y ordenar elementos</u>

- `np.sort(array)`: Ordena
- `np.concatenate(array1, array2)`: une dos vectores
    - Pueden unirse en el eje vertical: `axis = 0` (se apilan uno sobre el otro)
    - Pueden unirse en el eje horizontal: `axis = 1` (se pegan cabeza con cola)

<u>Conocer el tamaño, dimensiones y forma de un arreglo</u>
- `ndarray.dim`: te dice la cantidad de dimensiones
- `ndarray.shape`: te da la forma en forma de tupla
- `ndarray.size`: te devuelve la cantidad de elementos (producto de la tupla)

<u>Cambiar la forma de un arreglo</u>
- `ndarray.reshape(valores)`: modifica la matriz o vector para que coincida con las nuevas dimensiones

<u>Agregar un nuevo eje a un arreglo</u>
- `array[np.newaxis, :]` o `array[np.newaxis, :]`: agrega dimensión extra para pasar de un vector a una matriz de (1, n) o (n, 1)
<u>Índices y rebanadas</u>
Igual que con las listas. Adicionalmente se pueden hacer *consultas*
- `a[condicion para a]` -> devuelve un array con el resultado (**filtro**)
- Para más de una condición se concatenan usando `&` y `|`
- `np.nonzero(condicion)`: devuelve las coordenadas de los elementos alcanzados por la condición.
    - devuelve tupla de arreglos, uno por cada dimensión.
    - para armar lista de coord: `lista_coord = list(zip(b[0],b[1]))`

Existe también el método `copy` para no pisar memoria como pasaba con las listas.

In [37]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a
a[0][0] = 100
print(a)
print(b)

[[100   2   3]
 [  4   5   6]]
[[100   2   3]
 [  4   5   6]]


In [38]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.copy()
a[0][0] = 100
print(a)
print(b)

[[100   2   3]
 [  4   5   6]]
[[1 2 3]
 [4 5 6]]


También funcionan los `max, min, sum` de listas

In [50]:
array1 = np.array([1, 2, 3, 4, 5])
array3 = np.array([[1, 2, 3], [4, 5, 6]])
print(sum(array1))
print(array1.sum())
print(array1.sum(axis = 0))
print('')
print(sum(array3))
print(array3.sum(axis = 0))
print(array3.sum(axis = 1))

15
15
15

[5 7 9]
[5 7 9]
[ 6 15]


Vemos que la suma se realiza de acuerdo al eje que le digamos a `.sum()`

##  Broadcasting

In [51]:
array = np.array([1, 1, 1])
array * 2

array([2, 2, 2])

In [57]:
array1 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
array3 = np.array([4, 5, 4])
array1 * array3

array([[ 4,  5,  4],
       [ 8, 10,  8],
       [12, 15, 12]])

Podemos ver en estos ejemplos que las multiplicaciones se dan coordenada a coordenada (1ro con 1ro, 2do con 2do, ...)

Sumamos más funciones:
 - ndarray.max()
 - ndarray.min()
 - ndarray.mean()
 - ndarray.std()
 - ndarray.prod()

In [64]:
array1 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print(array1.sum())
print(array1.sum(axis = 0))
print(array1.sum(axis = 1))

18
[6 6 6]
[3 6 9]


## Guardar y cargas objetos de numpy

Tenemos dos maneras de guardar nuestros objetos de numpy:
 - En formato texto (tanto `.txt` como `.csv`)
     - `np.savetext('filename.txt', variable)`
     - `foo = np.loadtext('filename.txt')`
 - En formato binario (`.npy`)
     - `np.save('filename', variable)`
     - `foo = np.load('filename.npy')`